name: ledfx
description: "Record Audio Stream from your (Android) device and control WLED device"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  n_dimensional_array: ^1.0.4
  matrix2d: ^1.0.4
  http: ^1.5.0
  equatable: ^2.0.7
  nanoid: ^1.0.0
  ffi: ^2.1.4
  hooks: ^0.20.1
  code_assets: ^0.19.7
  logging: ^1.3.0
  native_toolchain_cmake: ^0.1.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  ffigen: ^19.1.0

flutter:
  uses-material-design: true

aubio_config:
  defines:
    common:
      AUBIO_BUILD_SHARED: "ON"
      CMAKE_BUILD_TYPE: "Release"
      # Disable unnecessary features to reduce size
      AUBIO_BUILD_TESTS: "OFF"
      AUBIO_BUILD_EXAMPLES: "OFF"
      AUBIO_BUILD_DOC: "OFF"
      AUBIO_BUILD_TOOLS: "OFF"
      # Core audio analysis features - enable what you need
      AUBIO_ENABLE_ONSET: "ON"
      AUBIO_ENABLE_PITCH: "ON"
      AUBIO_ENABLE_TEMPO: "ON"
      AUBIO_ENABLE_NOTES: "ON"
      AUBIO_ENABLE_MFCC: "ON"
      AUBIO_ENABLE_FFT: "ON"
      # Disable external dependencies to simplify build
      AUBIO_DISABLE_AVCODEC: "ON"
      AUBIO_DISABLE_SNDFILE: "ON"
      AUBIO_DISABLE_SAMPLERATE: "ON"
      AUBIO_DISABLE_JACK: "ON"
      AUBIO_DISABLE_FFTW3: "ON"
      # Enable built-in simple wav support
      AUBIO_ENABLE_WAVREAD: "ON"
      AUBIO_ENABLE_WAVWRITE: "ON"
    android:
      ANDROID_ARM_NEON: "TRUE"
      # CMAKE_ANDROID_ARCH_ABI: "arm64-v8a"
    ios:
      # CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
    macos:
      # CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
    linux: {}
  options:
    build_local: false
